[workspace]
members = ["gtk4-layer-shell", "gtk4-layer-shell-sys"]
exclude = ["gir"]
resolver = "2"

[workspace.package]
authors = ["pentamassiv <pentamassiv@posteo.de>"]
rust-version = "1.70"
edition = "2021"
license = "MIT"

[workspace.dependencies]
libc = "0.2"
bitflags = "2.0"
glib-sys = "0.19"
glib = "0.19"
gio = "0.19"
gdk4-sys = "0.8"
gdk = { package = "gdk4", version = "0.8" }
gtk4-sys = "0.8"
gtk = { package = "gtk4", version = "0.8" }
system-deps = "6"
shell-words = "1.0"
tempfile = "3"
libadwaita = "0.6"
relm4 = "0.8"
gtk4-layer-shell-sys = { path = "gtk4-layer-shell-sys", version = "0.2" }
